class Config:
    SECRET_KEY = '#12345ABCDE'
    SQLALCHEMY_DATABASE_URI = 'sqlite:///msa.sqlite3'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    GEMINI_API_KEY = "AIzaSyD62UgmDbskWTX7iTxKwJ1s_7mwNGC5ax8"